spring:
  application:
    name: ms-proveedor

  datasource:
    #Mapeado al contenedor 'mi-mysql-servicios' y a la BD 'proveedor' según tu compose
    url: ${DB_URL:jdbc:mysql://localhost:3306/proveedor?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${PORT:8082}
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: info
    duoc:
      cl:
        proveedor: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/proveedores.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    service-url:
      #Cambiado para apuntar al host 'eureka-server' de tu compose
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true