version: '3.8'

networks:
  ms-net:
    driver: bridge

services:
  # ── EUREKA (Service Discovery) ──────────────────────────────
  eureka-server:
    build:
      context: ./eureka/eureka
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - ms-net
    deploy:
      resources:
        limits:
          memory: 400M

  # ── BASE DE DATOS (compartida) ──────────────────────────────
  mi-mysql:
    image: mysql:8.0
    container_name: mi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - ms-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 1G


  # ── MICROSERVICIOS ──────────────────────────────────────────
  ms-categoria:
    build:
      context: ./categorias
      dockerfile: Dockerfile
    container_name: ms-categoria
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://mi-mysql:3306/db_categorias?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - DB_USER=root
      - DB_PASS=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ms-net
    depends_on:
      mi-mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 400M

  ms-producto:
    build:
      context: ./productos
      dockerfile: Dockerfile
    container_name: ms-producto
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://mi-mysql:3306/db_productos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - DB_USER=root
      - DB_PASS=root
      - API_PROVEEDORES_URL=http://ms-proveedor:8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ms-net
    depends_on:
      mi-mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 400M

  ms-cliente:
    build:
      context: ./clientes
      dockerfile: Dockerfile
    container_name: ms-cliente
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:mysql://mi-mysql:3306/cliente_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - MICROSERVICIOS_PEDIDOS_URL=http://ms-pedido:8084
      - MICROSERVICIOS_DESPACHO_URL=http://ms-despacho:8089
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ms-net
    depends_on:
      mi-mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 400M

  ms-pedido:
    build:
      context: ./pedidos
      dockerfile: Dockerfile
    container_name: ms-pedido
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://mi-mysql:3306/pedidos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - DB_USER=root
      - DB_PASS=root
      - API_PRODUCTOS_URL=http://ms-producto:8081/api/v1/
      - API_CLIENTES_URL=http://ms-cliente:8086/api
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ms-net
    depends_on:
      mi-mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 400M

  ms-pago:
    build:
      context: ./pagos
      dockerfile: Dockerfile
    container_name: ms-pago
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:mysql://mi-mysql:3306/pago_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - PEDIDOS_SERVICE_URL=http://ms-pedido:8084
      - CLIENTES_SERVICE_URL=http://ms-cliente:8086
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ms-net
    depends_on:
      mi-mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 400M

  ms-inventario:
    build:
      context: ./inventarios
      dockerfile: Dockerfile
    container_name: ms-inventario
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://mi-mysql:3306/db_inventarios?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USER=root
      - DB_PASS=root
      - API_PRODUCTOS_URL=http://ms-producto:8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ms-net
    depends_on:
      mi-mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 400M

  ms-proveedor:
    build:
      context: ./proveedor
      dockerfile: Dockerfile
    container_name: ms-proveedor
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://mi-mysql:3306/proveedor?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USER=root
      - DB_PASS=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ms-net
    depends_on:
      mi-mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 400M

  ms-catalogo:
    build:
      context: ./catalogo
      dockerfile: Dockerfile
    container_name: ms-catalogo
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://mi-mysql:3306/catalogo?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - DB_USER=root
      - DB_PASS=root
      - API_PRODUCTOS_URL=http://ms-producto:8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ms-net
    depends_on:
      mi-mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 400M

  ms-resena:
    build:
      context: ./reseñas
      dockerfile: Dockerfile
    container_name: ms-resena
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://mi-mysql:3306/db_resenas?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - DB_USER=root
      - DB_PASS=root
      - API_CLIENTES_URL=http://ms-cliente:8086
      - API_PAGOS_URL=http://ms-pago:8085
      - API_PEDIDOS_URL=http://ms-pedido:8084
      - API_PRODUCTOS_URL=http://ms-producto:8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ms-net
    depends_on:
      mi-mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 400M

  ms-despacho:
    build:
      context: ./despachos
      dockerfile: Dockerfile
    container_name: ms-despacho
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=mi-mysql
      - MYSQL_DATABASE=db_despachos
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - API_PEDIDOS_URL=http://ms-pedido:8084
      - API_PROVEEDORES_URL=http://ms-proveedor:8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ms-net
    depends_on:
      mi-mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 400M

  # ── API GATEWAY ────────────────────────────────────────────
  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - ms-net
    depends_on:
      - eureka-server
    deploy:
      resources:
        limits:
          memory: 400M

