server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
     routes:
       - id: rut-productos
         uri: lb://MS-PRODUCTO
         predicates:
          - Path=/api/v1/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
