spring.application.name=eureka
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

#desactivar el modo de autopreservacion
eureka.server.enable-self-preservation=false
#tiempo en milisegundos que espera eureka para escanear
# y limpiar servicios caidos (ej 2 segundos)
eureka.server.eviction-interval-timer-in-ms=2000