networks:
  microservicios-net:
    driver: bridge
 
services:
  # --- BASES DE DATOS ---
  db-productos:
    image: mysql
    environment:
      MYSQL_DATABASE: db_productos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
 
  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - microservicios-net
 
  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - microservicios-net
 
  productos:
    build: ./productos
    container_name: productos
    depends_on:
      db-productos:
        condition: service_healthy
      eureka:
        condition: service_started
      categorias:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-productos:3306/db_productos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - CATEGORIAS_API_URL=http://categorias:8083/api/v1
    networks:
      - microservicios-net