spring.application.name=ms-proveedor
server.port=8082

# 1.permisos de Clave Pública y SSL desactivado
spring.datasource.url=jdbc:mysql://localhost:3306/proveedor?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# 2. JPA: mantenemos en 'none' porque Flyway manda, pero activamos logs para ver qué pasa
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# 3. Errores
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

# 4. Flyway (Agregamos el baseline)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Esto evita errores si la DB ya existe pero no tiene tablas de Flyway
spring.flyway.baseline-on-migrate=true