spring:
  profiles:
    active: dev
  application:
    name: ms-resena

springdoc:
  api-docs:
    path: /api/v1/resenas-docs
  swagger-ui:
    path: /api/v1/resenas-swagger

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/db_resenas?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

api:
  clientes:
    url: http://localhost:8086
  pagos:
    url: http://localhost:8085
  pedidos:
    url: http://localhost:8084
  productos:
    url: http://localhost:8081

logging:
  level:
    root: INFO
    cl.jorge.resena: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${PORT:8087}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

api:
  clientes:
    url: http://${CLIENTES_SERVICE_HOST:localhost}:8086
  pagos:
    url: http://${PAGOS_SERVICE_HOST:localhost}:8085
  pedidos:
    url: http://${PEDIDOS_SERVICE_HOST:localhost}:8084
  productos:
    url: http://${PRODUCTOS_SERVICE_HOST:localhost}:8081

logging:
  level:
    root: WARN
